version: '2'
services:
  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    image: approach-api:latest
    container_name: approach-api
    environment:
      CONTAINER_ROLE: app
      DB_HOST: '${DB_HOST}'
      DB_PORT: '${DB_PORT}'
      DB_DATABASE: '${DB_DATABASE}'
      DB_USERNAME: '${DB_USERNAME}'
      DB_PASSWORD: '${DB_PASSWORD}'
      APP_ENV: '${APP_ENV}'
      APP_KEY: '${APP_KEY}'
      APP_DEBUG: '${APP_DEBUG}'
      BROADCAST_DRIVER: '$BROADCAST_DRIVER'
      CACHE_DRIVER: '${CACHE_DRIVER}'
      QUEUE_DRIVER: '${QUEUE_DRIVER}'
      JWT_SECRET: '${JWT_SECRET}'
      PUSHER_APP_ID: '${PUSHER_APP_ID}'
      PUSHER_APP_KEY: '${PUSHER_APP_KEY}'
      PUSHER_APP_SECRET: '${PUSHER_APP_SECRET}'
      PUSHER_APP_CLUSTER: '${PUSHER_APP_CLUSTER}'
      PUSHER_APP_USE_TLS: '${PUSHER_APP_USE_TLS}'
      S3_KEY: '${S3_KEY}'
      S3_SECRET: '${S3_SECRET}'
      S3_REGION: '${S3_REGION}'
      S3_BUCKET: '${S3_BUCKET}'
      SNS_KEY: '${SNS_KEY}'
      SNS_REGION: '${SNS_REGION}'
      SNS_SECRET: '${SNS_SECRET}'
      ANDROID_APPLICATION_ARN: '${ANDROID_APPLICATION_ARN}'
      IOS_APPLICATION_ARN: '${IOS_APPLICATION_ARN}'
      GOOGLE_CLIENT_ID_ANDROID: '${GOOGLE_CLIENT_ID_ANDROID}'
      GOOGLE_CLIENT_ID_IOS: '${GOOGLE_CLIENT_ID_IOS}'
      #      GOOGLE_APP_SECRET: '${GOOGLE_APP_SECRET}'
      #      GOOGLE_REDIRECT_URI: '${GOOGLE_REDIRECT_URI}'
      SQS_KEY: '${SQS_KEY}'
      SQS_REGION: '${SQS_REGION}'
      SQS_SECRET: '${SQS_SECRET}'
      SQS_PREFIX: '${SQS_PREFIX}'
      SQS_QUEUE: '${SQS_QUEUE}'
      MAIL_MAILER: '${MAIL_MAILER}'
      MAIL_HOST: '${MAIL_HOST}'
      MAIL_PORT: '${MAIL_PORT}'
      MAIL_USERNAME: '${MAIL_USERNAME}'
      MAIL_PASSWORD: '${MAIL_PASSWORD}'
      MAIL_ENCRYPTION: '${MAIL_ENCRYPTION}'
      MAIL_FROM_ADDRESS: '${MAIL_FROM_ADDRESS}'
      MAIL_FROM_NAME: '${MAIL_FROM_NAME}'
    volumes:
      - .:/var/www/html
    ports:
      - 8030:80
  scheduler:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    image: approach-api:latest
    container_name: approach-api-scheduler
    environment:
      CONTAINER_ROLE: scheduler
      DB_HOST: '${DB_HOST}'
      DB_PORT: '${DB_PORT}'
      DB_DATABASE: '${DB_DATABASE}'
      DB_USERNAME: '${DB_USERNAME}'
      DB_PASSWORD: '${DB_PASSWORD}'
      APP_ENV: '${APP_ENV}'
      APP_KEY: '${APP_KEY}'
      APP_DEBUG: '${APP_DEBUG}'
      TZ: '${TZ}'
      BROADCAST_DRIVER: '$BROADCAST_DRIVER'
      CACHE_DRIVER: '${CACHE_DRIVER}'
      QUEUE_DRIVER: '${QUEUE_DRIVER}'
      JWT_SECRET: '${JWT_SECRET}'
      PUSHER_APP_ID: '${PUSHER_APP_ID}'
      PUSHER_APP_KEY: '${PUSHER_APP_KEY}'
      PUSHER_APP_SECRET: '${PUSHER_APP_SECRET}'
      PUSHER_APP_CLUSTER: '${PUSHER_APP_CLUSTER}'
      PUSHER_APP_USE_TLS: '${PUSHER_APP_USE_TLS}'
      S3_KEY: '${S3_KEY}'
      S3_SECRET: '${S3_SECRET}'
      S3_REGION: '${S3_REGION}'
      S3_BUCKET: '${S3_BUCKET}'
      SNS_KEY: '${SNS_KEY}'
      SNS_REGION: '${SNS_REGION}'
      SNS_SECRET: '${SNS_SECRET}'
      ANDROID_APPLICATION_ARN: '${ANDROID_APPLICATION_ARN}'
      IOS_APPLICATION_ARN: '${IOS_APPLICATION_ARN}'
      GOOGLE_CLIENT_ID_ANDROID: '${GOOGLE_CLIENT_ID_ANDROID}'
      GOOGLE_CLIENT_ID_IOS: '${GOOGLE_CLIENT_ID_IOS}'
      #      GOOGLE_APP_SECRET: '${GOOGLE_APP_SECRET}'
      #      GOOGLE_REDIRECT_URI: '${GOOGLE_REDIRECT_URI}'
      SQS_KEY: '${SQS_KEY}'
      SQS_REGION: '${SQS_REGION}'
      SQS_SECRET: '${SQS_SECRET}'
      SQS_QUEUE: '${SQS_QUEUE}'
      MAIL_MAILER: '${MAIL_MAILER}'
      MAIL_HOST: '${MAIL_HOST}'
      MAIL_PORT: '${MAIL_PORT}'
      MAIL_USERNAME: '${MAIL_USERNAME}'
      MAIL_PASSWORD: '${MAIL_PASSWORD}'
      MAIL_ENCRYPTION: '${MAIL_ENCRYPTION}'
      MAIL_FROM_ADDRESS: '${MAIL_FROM_ADDRESS}'
      MAIL_FROM_NAME: '${MAIL_FROM_NAME}'
  queue:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    image: approach-api:latest
    container_name: approach-api-queue
    environment:
      CONTAINER_ROLE: queue
      DB_HOST: '${DB_HOST}'
      DB_PORT: '${DB_PORT}'
      DB_DATABASE: '${DB_DATABASE}'
      DB_USERNAME: '${DB_USERNAME}'
      DB_PASSWORD: '${DB_PASSWORD}'
      APP_ENV: '${APP_ENV}'
      APP_KEY: '${APP_KEY}'
      APP_DEBUG: '${APP_DEBUG}'
      BROADCAST_DRIVER: '$BROADCAST_DRIVER'
      CACHE_DRIVER: '${CACHE_DRIVER}'
      QUEUE_DRIVER: '${QUEUE_DRIVER}'
      JWT_SECRET: '${JWT_SECRET}'
      PUSHER_APP_ID: '${PUSHER_APP_ID}'
      PUSHER_APP_KEY: '${PUSHER_APP_KEY}'
      PUSHER_APP_SECRET: '${PUSHER_APP_SECRET}'
      PUSHER_APP_CLUSTER: '${PUSHER_APP_CLUSTER}'
      PUSHER_APP_USE_TLS: '${PUSHER_APP_USE_TLS}'
      S3_KEY: '${S3_KEY}'
      S3_SECRET: '${S3_SECRET}'
      S3_REGION: '${S3_REGION}'
      S3_BUCKET: '${S3_BUCKET}'
      SNS_KEY: '${SNS_KEY}'
      SNS_REGION: '${SNS_REGION}'
      SNS_SECRET: '${SNS_SECRET}'
      ANDROID_APPLICATION_ARN: '${ANDROID_APPLICATION_ARN}'
      IOS_APPLICATION_ARN: '${IOS_APPLICATION_ARN}'
      GOOGLE_CLIENT_ID_ANDROID: '${GOOGLE_CLIENT_ID_ANDROID}'
      GOOGLE_CLIENT_ID_IOS: '${GOOGLE_CLIENT_ID_IOS}'
      #      GOOGLE_APP_SECRET: '${GOOGLE_APP_SECRET}'
      #      GOOGLE_REDIRECT_URI: '${GOOGLE_REDIRECT_URI}'
      SQS_KEY: '${SQS_KEY}'
      SQS_REGION: '${SQS_REGION}'
      SQS_SECRET: '${SQS_SECRET}'
      SQS_PREFIX: '${SQS_PREFIX}'
      SQS_QUEUE: '${SQS_QUEUE}'
      MAIL_MAILER: '${MAIL_MAILER}'
      MAIL_HOST: '${MAIL_HOST}'
      MAIL_PORT: '${MAIL_PORT}'
      MAIL_USERNAME: '${MAIL_USERNAME}'
      MAIL_PASSWORD: '${MAIL_PASSWORD}'
      MAIL_ENCRYPTION: '${MAIL_ENCRYPTION}'
      MAIL_FROM_ADDRESS: '${MAIL_FROM_ADDRESS}'
      MAIL_FROM_NAME: '${MAIL_FROM_NAME}'
